# Data Exploration

In this script we put various informative plots or derive important figures (like number of full data points, etc). None of these scripts make changes to the data or do complex analysis; just explore base dataset

# GCproperties.csv

This file contains cluster-level info on our sample. Let's load up GCproperties file and see what it looks like:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from IPython.core.magic import register_cell_magic

@register_cell_magic
def skip(line, cell):
    return


data_folder='../../Datasets/Original_Datasets'
GCprop=pd.read_csv(f'{data_folder}/GCproperties.csv', encoding='latin1')
GCprop.head()

,#Name,mu_alpha,mu_alpha_err,mu_delta,mu_delta_err,V_los,V_los_err,R_apo,R_apo_err,R_peri,...,sigma+err_Kirby,sigma-err_Kirby,FeH_supp,FeH+err_supp,FeH-err_supp,sigma_FeH,sigma_FeH+err,sigma_FeH-err,FeH_Ref,FeH_notes
0,# Units: mas/yr (proper motions),km/s (velocity),kpc (R_apo,R_peri),1e5 Msun (M_i),pc (r_J),NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,# Refs: (1) Dinescu et al. (1997); (2) Dinescu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,# (6) Casetti-Dinescu et al. (2010); (7) Caset...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"# (12) Willman & Strader (2012), (13) Worley &...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"# (16) Pohl (2015; PhD), (17) Villanova et al....",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

A lot of this file is actually notes on where the data is from,  not the actual data. So we drop all columns with NA for age, this gets rid of all that and also where we actually have NA for age

In [2]:
GC_leftover=GCprop.dropna(subset=['age_Kruijssen'])

# NGC_combi.csv

This file contains our main dataset, before being split into test/train

In [3]:
combined_data='../Datasets/Original_Datasets/NGC_combi.csv'
df_full=pd.read_csv(combined_data)
df_full=df_full.set_index('Star ID') #this is a unique identifier for each star, instead of each cluster
df_full.rename(columns={'F435W': 'F438W', 'F435W_abs':'F438W_abs', 'F435W_e':'F438W_e'}, inplace=True)   #the F438 filter is misnamed in these files for some reason

#### Check for repeat data:

In [4]:
num_mentions=df_full.index.value_counts()
print(num_mentions)
print(f'Some data is repeated {num_mentions.iloc[0]} times! Other data repeated {num_mentions.iloc[1]} times...not sure yet what to do with this. For now, taking all repeate data completely out when doig train/test split')

Star ID
6.08E+18    60
R0000101     4
R0000373     4
R0000404     4
R0001674     4
            ..
R0004771     1
R0004780     1
R0004864     1
R0004884     1
R0003433     1
Name: count, Length: 858, dtype: int64
Some data is repeated 60 times! Other data repeated 4 times...not sure yet what to do with this. For now, taking all repeate data completely out when doig train/test split

Also, the data point that is repeated 60 times has a weird Star ID.

In [5]:
num_mentions.index

Index(['6.08E+18', 'R0000101', 'R0000373', 'R0000404', 'R0001674', 'R0000781',
       'R0001469', 'R0000346', 'R0000181', 'R0002301',
       ...
       'R0004346', 'R0004479', 'R0004732', 'R0004739', 'R0004737', 'R0004771',
       'R0004780', 'R0004864', 'R0004884', 'R0003433'],
      dtype='object', name='Star ID', length=858)

Print info on the two most-repeated data points:

In [6]:
df_full.loc[num_mentions.index[0]]

,NGC,Paper,Author Reference,RAJ2000,DEJ2000,Distance (pc),neg_sigma_dist,pos_sigma_dist,Vmag,Vmag_abs,...,F336W_e,F438W,F438W_abs,F438W_e,F606W,F606W_abs,F606W_e,F814W,F814W_abs,F814W_e
Star ID,,,,,,,,,,,,,,,,,,,,,
6.08E+18,5139,Mucciarelli,150704,201.708583,-47.513114,5426,-47,47,14.885,1.212601,...,0.0071,15.8378,2.165401,0.0094,14.7228,1.050401,NaN,13.9047,0.232301,0.0075
6.08E+18,5139,Mucciarelli,150996,201.736107,-47.512880,5426,-47,47,14.836,1.163601,...,0.0079,15.7425,2.070101,0.0094,14.5959,0.923501,NaN,13.7791,0.106701,0.0075
6.08E+18,5139,Mucciarelli,158663,201.711761,-47.506769,5426,-47,47,14.671,0.998601,...,0.0109,15.4938,1.821401,0.0088,14.4352,0.762801,NaN,13.6885,0.016101,0.0075
6.08E+18,5139,Mucciarelli,159324,201.729075,-47.506264,5426,-47,47,15.341,1.668601,...,0.0059,16.4917,2.819301,0.0109,15.0914,1.419001,NaN,14.2593,0.586901,0.0075
6.08E+18,5139,Mucciarelli,159562,201.672705,-47.506047,5426,-47,47,14.846,1.173601,...,0.0067,15.7204,2.048001,0.0092,14.5591,0.886701,NaN,13.7093,0.036901,NaN
6.08E+18,5139,Mucciarelli,160787,201.727712,-47.505054,5426,-47,47,15.025,1.352601,...,0.0069,16.0554,2.383001,0.0098,14.8595,1.187101,NaN,14.0602,0.387801,0.0075
6.08E+18,5139,Mucciarelli,161739,201.718227,-47.504266,5426,-47,47,15.088,1.415601,...,0.0059,16.0605,2.388101,0.0098,14.8078,1.135401,NaN,14.0464,0.374001,0.0075
6.08E+18,5139,Mucciarelli,162743,201.679732,-47.503383,5426,-47,47,14.800,1.127601,...,0.0077,15.5828,1.910401,0.0089,14.6010,0.928601,NaN,13.8528,0.180401,NaN
6.08E+18,5139,Mucciarelli,165409,201.687549,-47.501240,5426,-47,47,15.189,1.516601,...,0.0058,15.9978,2.325401,0.0074,14.8718,1.199401,0.0064,14.0587,0.386301,NaN
6.08E+18,5139,Mucciarelli,167987,201.740228,-47.499217,5426,-47,47,14.794,1.121601,...,0.0063,15.8308,2.158401,0.0094,14.5390,0.866601,NaN,13.6709,-0.001499,0.0089
6.08E+18,5139,Mucciarelli,171666,201.703795,-47.496217,5426,-47,47,15.162,1.489601,...,0.0057,16.3241,2.651701,0.0075,14.9248,1.252401,0.0064,14.0673,0.394901,NaN
6.08E+18,5139,Mucciarelli,171735,201.726400,-47.496132,5426,-47,47,15.539,1.866601,...,0.0059,16.4646,2.792201,0.0071,15.2366,1.564201,NaN,14.4005,0.728101,0.0089
6.08E+18,5139,Mucciarelli,171873,201.716862,-47.496020,5426,-47,47,15.025,1.352601,...,0.0057,15.8450,2.172601,0.0076,14.7368,1.064401,NaN,13.8988,0.226401,NaN
6.08E+18,5139,Mucciarelli,173824,201.718800,-47.494447,5426,-47,47,15.220,1.547601,...,0.0056,16.1308,2.458401,0.0074,14.9704,1.298001,NaN,14.1450,0.472601,NaN
6.08E+18,5139,Mucciarelli,175717,201.679422,-47.492907,5426,-47,47,15.295,1.622601,...,0.0057,16.0778,2.405401,0.0074,14.9292,1.256801,0.0064,14.1042,0.431801,NaN
6.08E+18,5139,Mucciarelli,177226,201.740126,-47.491647,5426,-47,47,14.773,1.100601,...,0.0061,15.6353,1.962901,0.0090,14.5040,0.831601,NaN,13.6969,0.024501,0.0089
6.08E+18,5139,Mucciarelli,178454,201.720370,-47.490685,5426,-47,47,15.109,1.436601,...,0.0058,16.0423,2.369901,0.0074,14.9180,1.245601,0.0064,14.0552,0.382801,NaN
6.08E+18,5139,Mucciarelli,181727,201.674809,-47.487972,5426,-47,47,15.070,1.397601,...,0.0056,16.0455,2.373101,0.0074,14.8558,1.183401,0.0064,14.0299,0.357501,NaN
6.08E+18,5139,Mucciarelli,182211,201.680785,-47.487585,5426,-47,47,15.023,1.350601,...,0.0108,15.9270,2.254601,0.0096,14.8115,1.139101,0.0064,13.9869,0.314501,NaN
6.08E+18,5139,Mucciarelli,183176,201.755039,-47.486839,5426,-47,47,14.974,1.301601,...,0.0062,15.8259,2.153501,0.0094,14.6433,0.970901,NaN,13.8072,0.134801,0.0075
6.08E+18,5139,Mucciarelli,185089,201.693389,-47.485297,5426,-47,47,14.891,1.218601,...,0.0055,15.7675,2.095101,0.0093,14.6681,0.995701,0.0064,13.8388,0.166401,NaN
6.08E+18,5139,Mucciarelli,185698,201.717415,-47.484743,5426,-47,47,14.929,1.256601,...,0.0055,15.9704,2.298001,0.0079,14.7082,1.035801,0.0064,13.8640,0.191601,NaN
6.08E+18,5139,Mucciarelli,186008,201.735237,-47.484481,5426,-47,47,14.889,1.216601,...,0.0058,15.7449,2.072501,0.0092,14.6359,0.963501,0.0064,13.7962,0.123801,NaN
6.08E+18,5139,Mucciarelli,186775,201.746094,-47.483853,5426,-47,47,15.121,1.448601,...,0.0072,16.0121,2.339701,0.0074,14.8482,1.175801,NaN,14.0307,0.358301,0.0090
6.08E+18,5139,Mucciarelli,187928,201.692978,-47.482784,5426,-47,47,15.002,1.329601,...,0.0055,15.8639,2.191501,NaN,14.7261,1.053701,0.0064,13.8922,0.219801,NaN
6.08E+18,5139,Mucciarelli,188238,201.667021,-47.482539,5426,-47,47,15.112,1.439601,...,0.0056,15.9890,2.316601,0.0074,14.7881,1.115701,0.0067,13.9738,0.301401,NaN
6.08E+18,5139,Mucciarelli,189192,201.751660,-47.481797,5426,-47,47,15.307,1.634601,...,0.0061,16.3319,2.659501,0.0105,15.0481,1.375701,NaN,14.2291,0.556701,0.0081
6.08E+18,5139,Mucciarelli,192390,201.673885,-47.479166,5426,-47,47,14.726,1.053601,...,0.0056,15.6411,1.968701,0.0090,14.5106,0.838201,0.0064,13.6906,0.018201,NaN
6.08E+18,5139,Mucciarelli,193160,201.717685,-47.478503,5426,-47,47,15.376,1.703601,...,0.0055,16.3080,2.635601,0.0105,15.1602,1.487801,0.0065,14.3527,0.680301,0.0066
6.08E+18,5139,Mucciarelli,193903,201.689078,-47.477838,5426,-47,47,14.951,1.278601,...,0.0055,15.7725,2.100101,0.0093,14.5985,0.926101,0.0064,13.7743,0.101901,NaN
6.08E+18,5139,Mucciarelli,194059,201.734983,-47.477774,5426,-47,47,15.178,1.505601,...,0.0059,16.1188,2.446401,0.0103,14.9092,1.236801,0.0064,14.0935,0.421101,NaN
6.08E+18,5139,Mucciarelli,196032,201.746604,-47.476078,5426,-47,47,14.775,1.102601,...,0.0077,15.6616,1.989201,0.0091,14.5176,0.845201,NaN,13.6791,0.006701,0.0089
6.08E+18,5139,Mucciarelli,197044,201.725065,-47.475227,5426,-47,47,14.971,1.298601,...,0.0056,15.8691,2.196701,0.0094,14.6911,1.018701,0.0064,13.8646,0.192201,NaN
6.08E+18,5139,Mucciarelli,198494,201.715021,-47.473944,5426,-47,47,14.799,1.126601,...,0.0058,15.7963,2.123901,0.0085,14.5791,0.906701,0.0064,13.7240,0.051601,NaN
6.08E+18,5139,Mucciarelli,200853,201.674486,-47.471874,5426,-47,47,14.767,1.094601,...,0.0056,15.6417,1.969301,0.0091,14.5100,0.837601,0.0064,13.6465,-0.025899,NaN
6.08E+18,5139,Mucciarelli,201236,201.760259,-47.471644,5426,-47,47,15.138,1.465601,...,0.0068,16.1400,2.467601,0.0100,14.8847,1.212301,NaN,13.9774,0.305001,0.0075
6.08E+18,5139,Mucciarelli,202859,201.678855,-47.470228,5426,-47,47,14.945,1.272601,...,0.0079,15.8283,2.155901,0.0701,14.7799,1.107501,0.0064,13.8772,0.204801,NaN
6.08E+18,5139,Mucciarelli,207115,201.646965,-47.466621,5426,-47,47,15.189,1.516601,...,0.0060,16.1003,2.427901,0.0100,14.9258,1.253401,NaN,14.1180,0.445601,NaN
6.08E+18,5139,Mucciarelli,207775,201.702913,-47.466158,5426,-47,47,14.999,1.326601,...,0.0058,15.8837,2.211301,0.0095,14.7837,1.111301,0.0064,13.9425,0.270101,NaN
6.08E+18,5139,Mucciarelli,210889,201.684699,-47.463560,5426,-47,47,14.762,1.089601,...,0.0059,15.6189,1.946501,0.0090,14.4788,0.806401,0.0064,13.6555,-0.016899,NaN
6.08E+18,5139,Mucciarelli,211701,201.725113,-47.462970,5426,-47,47,15.061,1.388601,...,0.0061,16.0664,2.394001,0.0237,14.8462,1.173801,NaN,13.9967,0.324301,NaN
6.08E+18,5139,Mucciarelli,212996,201.713033,-47.461871,5426,-47,47,15.085,1.412601,...,0.0117,16.0216,2.349201,0.0183,14.8347,1.162301,0.0064,13.9925,0.320101,NaN
6.08E+18,5139,Mucciarelli,213229,201.653733,-47.461651,5426,-47,47,15.004,1.331601,...,0.0072,15.8234,2.151001,0.0094,14.7028,1.030401,NaN,13.8678,0.195401,NaN
6.08E+18,5139,Mucciarelli,214272,201.675779,-47.460714,5426,-47,47,15.009,1.336601,...,0.0057,15.9304,2.258001,0.0096,14.6943,1.021901,0.0064,13.8583,0.185901,NaN
6.08E+18,5139,Mucciarelli,215378,201.643934,-47.459807,5426,-47,47,14.923,1.250601,...,0.0080,15.7852,2.112801,0.0093,14.6604,0.988001,NaN,13.8279,0.155501,0.0089
6.08E+18,5139,Mucciarelli,219724,201.719226,-47.456180,5426,-47,47,14.873,1.200601,...,0.0060,15.7253,2.052901,0.0092,14.6092,0.936801,NaN,13.7797,0.107301,NaN
6.08E+18,5139,Mucciarelli,220667,201.657844,-47.455229,5426,-47,47,14.855,1.182601,...,0.0068,15.6962,2.023801,0.0091,14.5626,0.890201,NaN,13.7152,0.042801,NaN
6.08E+18,5139,Mucciarelli,221812,201.697706,-47.454244,5426,-47,47,14.819,1.146601,...,0.0059,15.8102,2.137801,0.0093,14.6619,0.989501,0.0064,13.8159,0.143501,NaN
6.08E+18,5139,Mucciarelli,231185,201.725035,-47.446119,5426,-47,47,14.780,1.107601,...,0.0100,15.6588,1.986401,0.0091,14.5263,0.853901,NaN,13.6840,0.011601,NaN
6.08E+18,5139,Mucciarelli,231840,201.686285,-47.445594,5426,-47,47,15.414,1.741601,...,0.0065,16.5607,2.888301,0.0072,15.2121,1.539701,NaN,14.4127,0.740301,0.0075
6.08E+18,5139,Mucciarelli,236180,201.681944,-47.442000,5426,-47,47,15.442,1.769601,...,0.0079,16.4190,2.746601,0.0108,15.1646,1.492201,NaN,14.3476,0.675201,NaN
6.08E+18,5139,Mucciarelli,239683,201.714101,-47.439203,5426,-47,47,14.857,1.184601,...,0.0132,15.7636,2.091201,0.0093,14.6376,0.965201,NaN,13.7870,0.114601,0.0075
6.08E+18,5139,Mucciarelli,245263,201.720756,-47.434724,5426,-47,47,15.046,1.373601,...,0.0072,15.9603,2.287901,0.0096,14.8114,1.139001,NaN,13.9478,0.275401,0.0075
6.08E+18,5139,Mucciarelli,245339,201.750214,-47.434663,5426,-47,47,14.991,1.318601,...,0.0073,15.9399,2.267501,0.0096,14.7477,1.075301,NaN,13.9274,0.255001,0.0077
6.08E+18,5139,Mucciarelli,246441,201.747664,-47.433721,5426,-47,47,14.878,1.205601,...,0.0104,15.7628,2.090401,0.0093,14.6233,0.950901,NaN,13.7883,0.115901,0.0075
6.08E+18,5139,Mucciarelli,247138,201.712832,-47.433198,5426,-47,47,14.859,1.186601,...,0.0071,15.8034,2.131001,0.0093,14.6767,1.004301,NaN,13.8219,0.149501,0.0075
6.08E+18,5139,Mucciarelli,252291,201.742706,-47.428975,5426,-47,47,14.907,1.234601,...,0.0178,15.8188,2.146401,0.0093,14.6412,0.968801,NaN,13.8044,0.132001,0.0075
6.08E+18,5139,Mucciarelli,255963,201.726498,-47.425927,5426,-47,47,14.913,1.240601,...,0.0105,15.8114,2.139001,0.0079,14.7242,1.051801,NaN,13.8136,0.141201,0.0086
6.08E+18,5139,Mucciarelli,270600,201.725281,-47.413531,5426,-47,47,14.811,1.138601,...,0.0149,15.7235,2.051101,0.0075,14.6062,0.933801,NaN,13.7465,0.074101,0.0094
6.08E+18,5139,Mucciarelli,272252,201.728690,-47.412049,5426,-47,47,15.519,1.846601,...,0.0080,16.6668,2.994401,0.0116,15.3172,1.644801,NaN,14.3527,0.680301,0.0104

In [7]:
df_full.loc[num_mentions.index[1]]

,NGC,Paper,Author Reference,RAJ2000,DEJ2000,Distance (pc),neg_sigma_dist,pos_sigma_dist,Vmag,Vmag_abs,...,F336W_e,F438W,F438W_abs,F438W_e,F606W,F606W_abs,F606W_e,F814W,F814W_abs,F814W_e
Star ID,,,,,,,,,,,,,,,,,,,,,
R0000101,6121,Carretta,29848,245.892171,-26.551083,1851,-16,15,13.47,2.132968,...,0.0,14.8545,3.517468,0.0,13.0861,1.749068,0.0,11.8955,0.558468,0.0
R0000101,6121,Dorazi + Marino,29848,245.892191,-26.551086,1851,-16,15,NaN,NaN,...,0.0,14.8545,3.517468,0.0,13.0861,1.749068,0.0,11.8955,0.558468,0.0
R0000101,6121,MacLean,13170,245.892167,-26.551083,1851,-16,15,13.52,2.182968,...,0.0,14.8545,3.517468,0.0,13.0861,1.749068,0.0,11.8955,0.558468,0.0
R0000101,6121,Marino,29848,245.892191,-26.551086,1851,-16,15,13.52,2.182968,...,0.0,14.8545,3.517468,0.0,13.0861,1.749068,0.0,11.8955,0.558468,0.0

Weird, the most-repeated one has slightly different values for each entry, but the same source-- almost like the Star ID is actually a cluster identifier and there's 60 stars in the cluster. The other repeat makes more sense because theres a different source each time

In [8]:
df_full.loc[num_mentions.index[2]]

,NGC,Paper,Author Reference,RAJ2000,DEJ2000,Distance (pc),neg_sigma_dist,pos_sigma_dist,Vmag,Vmag_abs,...,F336W_e,F438W,F438W_abs,F438W_e,F606W,F606W_abs,F606W_e,F814W,F814W_abs,F814W_e
Star ID,,,,,,,,,,,,,,,,,,,,,
R0000373,6121,Carretta,30598,245.896600,-26.542350,1851,-16,15,11.999,0.661968,...,0.0,13.6705,2.333468,0.0,11.5831,0.246068,0.0,10.254,-1.083032,0.0
R0000373,6121,Dorazi + Marino,30598,245.896617,-26.542352,1851,-16,15,NaN,NaN,...,0.0,13.6705,2.333468,0.0,11.5831,0.246068,0.0,10.254,-1.083032,0.0
R0000373,6121,MacLean,14037,245.896667,-26.542306,1851,-16,15,12.050,0.712968,...,0.0,13.6705,2.333468,0.0,11.5831,0.246068,0.0,10.254,-1.083032,0.0
R0000373,6121,Marino,30598,245.896617,-26.542352,1851,-16,15,12.050,0.712968,...,0.0,13.6705,2.333468,0.0,11.5831,0.246068,0.0,10.254,-1.083032,0.0

Ok, so all the entries with 4 repeats are from the same 4 sources. All entries with 3 repeats are from 3/4 of these same sources.

In [9]:
df_full.loc[num_mentions.index[5]]

,NGC,Paper,Author Reference,RAJ2000,DEJ2000,Distance (pc),neg_sigma_dist,pos_sigma_dist,Vmag,Vmag_abs,...,F336W_e,F438W,F438W_abs,F438W_e,F606W,F606W_abs,F606W_e,F814W,F814W_abs,F814W_e
Star ID,,,,,,,,,,,,,,,,,,,,,
R0000781,6121,Dorazi + Marino,31376,245.912191,-26.534324,1851,-16,15,NaN,NaN,...,0.0,14.5838,3.246768,0.0,12.8638,1.526768,0.0,11.6851,0.348068,0.0
R0000781,6121,MacLean,17095,245.912167,-26.534306,1851,-16,15,13.29,1.952968,...,0.0,14.5838,3.246768,0.0,12.8638,1.526768,0.0,11.6851,0.348068,0.0
R0000781,6121,Marino,31376,245.912191,-26.534324,1851,-16,15,13.29,1.952968,...,0.0,14.5838,3.246768,0.0,12.8638,1.526768,0.0,11.6851,0.348068,0.0

Remove repeated data:

In [10]:
isduped=df_full.index.duplicated(keep=False)
df=df_full.iloc[~isduped]
print(df.shape)
print(df.columns)

(752, 41)
Index(['NGC', 'Paper', 'Author Reference', 'RAJ2000', 'DEJ2000',
       'Distance (pc)', 'neg_sigma_dist', 'pos_sigma_dist', 'Vmag', 'Vmag_abs',
       'Bmag', 'Bmag_abs', 'Imag', 'Imag_abs', 'Kmag', 'Kmag_abs', 'Teff',
       'logg', 'age_Kruijssen', 'Fe/H', 'Fe/H_e', 'Fe/H_o', 'O/Fe', 'O/Fe_e',
       'Na/Fe', 'Na/Fe_e', 'F275W', 'F275W_abs', 'F275W_e', 'F336W',
       'F336W_abs', 'F336W_e', 'F438W', 'F438W_abs', 'F438W_e', 'F606W',
       'F606W_abs', 'F606W_e', 'F814W', 'F814W_abs', 'F814W_e'],
      dtype='object')

So with repeats removed, have 752 datapoints. Also 41 columns!

### Check for 99s

Used 99/-99 as NaNs; should replace with actual NaNs now, but let's check:

In [11]:
needed_data=['Fe/H', 'Fe/H_e', 'O/Fe', 'F275W', 'F336W', 'F438W', 'F606W', 'F814W', 
             'F275W_abs', 'F336W_abs', 'F438W_abs', 'F606W_abs', 'F814W_abs','age_Kruijssen']
mins=[]
maxs=[]
for column in needed_data:
    mins.append(df[column].min())
    maxs.append(df[column].max())

if np.min(mins)<-99.99 or np.max(maxs)>99.99:
    print('Likely failed to replace value with NaNs')
else:
    print('Looks good!')

Looks good!

### Look at Data Sizes

In [12]:
y_values=['O/Fe', 'Na/Fe']
filters=['F275W_abs', 'F336W_abs', 'F438W_abs', 'F606W_abs', 'F814W_abs']
df[y_values].describe()

             O/Fe       Na/Fe
count  566.000000  683.000000
mean     0.171186    0.340912
std      0.316409    0.272038
min     -0.913000   -0.420000
25%      0.000000    0.117500
50%      0.217500    0.366000
75%      0.399420    0.530000
max      0.918000    1.384000

In [13]:
df[filters].describe()

        F275W_abs   F336W_abs   F438W_abs   F606W_abs   F814W_abs
count  596.000000  595.000000  581.000000  744.000000  747.000000
mean     4.532625    2.306972    1.370791   -0.074828   -1.095255
std      1.446690    1.347590    1.354845    1.714413    1.743485
min      2.364362    0.377162   -1.161438   -2.886038   -4.195690
25%      3.648809    1.455972    0.393025   -1.246360   -2.286996
50%      4.246253    2.088585    1.146855   -0.253930   -1.286921
75%      5.031687    2.749293    2.218585    0.786917   -0.135991
max     14.220168   12.240468    9.921285    9.645368    8.108690

In [14]:
df_y=df.dropna(subset=y_values)                           
df_y[y_values].describe()

             O/Fe       Na/Fe
count  527.000000  527.000000
mean     0.163545    0.352443
std      0.320878    0.270165
min     -0.913000   -0.420000
25%     -0.010750    0.132000
50%      0.210000    0.377000
75%      0.397682    0.530000
max      0.908415    1.384000

Number of points with both y values

In [15]:
df_filters=df_y.dropna(subset=filters)
df_filters[filters].describe()

        F275W_abs   F336W_abs   F438W_abs   F606W_abs   F814W_abs
count  405.000000  405.000000  405.000000  405.000000  405.000000
mean     4.624964    2.197596    1.137571   -0.538219   -1.583349
std      1.371252    1.158704    1.224340    1.335193    1.408666
min      2.412162    0.377162   -1.161438   -2.883138   -4.195690
25%      3.739579    1.373881    0.166007   -1.537327   -2.624260
50%      4.300150    1.976401    0.914198   -0.694321   -1.754799
75%      5.140297    2.635782    1.860479    0.318383   -0.730317
max      8.512040    6.973785    7.088385    5.669685    4.842485

Number of points with both y values and all filters

In [16]:
other_xs=['age_Kruijssen', 'Fe/H']
df_x_y=df.dropna(subset=y_values+filters+other_xs)
df_x_y[other_xs].describe()

       age_Kruijssen        Fe/H
count     296.000000  296.000000
mean       11.830372   -1.433909
std         0.711953    0.500380
min        10.830000   -2.427000
25%        11.250000   -1.782000
50%        11.630000   -1.460000
75%        12.220000   -1.147750
max        13.060000   -0.398000

Number of points with both y values and all obvously useful x values. QUESTION: WHY DO WE NOT HAVE NORE METALLICITY DATA? OR AGE DATA? THIS SHOULD BE CLUSTER-WIDE PROPERTIES, ASSUMED HAD ALL THESE?

In [17]:
len(df['NGC'].unique())

27

Number of unique clusters

In [18]:
population=df_x_y['NGC'].value_counts()
print(population)

NGC
5139    56
2808    35
6388    32
6093    23
3201    16
6809    14
6254    13
362     13
1261    12
4590    12
288     10
7078    10
6205    10
6838    10
6934     7
6584     6
6121     6
7099     5
104      2
5904     2
6397     2
Name: count, dtype: int64

Cluster population

### How Many Points Have a Single Y-value?

In [19]:
for target in y_values:
    df_y=df.dropna(subset=target)
    print(df_y[target].describe())

count    566.000000
mean       0.171186
std        0.316409
min       -0.913000
25%        0.000000
50%        0.217500
75%        0.399420
max        0.918000
Name: O/Fe, dtype: float64
count    683.000000
mean       0.340912
std        0.272038
min       -0.420000
25%        0.117500
50%        0.366000
75%        0.530000
max        1.384000
Name: Na/Fe, dtype: float64

### How Many Points Have All Useful X-values and a Single Y-value?

Our dataset is not large. Probably need train/test split for each individual target.

In [20]:
for target in y_values:
    subset=filters+other_xs+[target]
    df_x_y=df.dropna(subset=subset)
    print(df_x_y[subset].describe())

        F275W_abs   F336W_abs   F438W_abs   F606W_abs   F814W_abs  \
count  323.000000  323.000000  323.000000  323.000000  323.000000
mean     4.637354    2.268769    1.275558   -0.362774   -1.391116
std      1.484420    1.213039    1.239410    1.345266    1.422614
min      2.364362    0.377162   -1.161438   -2.883138   -4.195690
25%      3.656722    1.375962    0.347390   -1.313798   -2.396396
50%      4.296607    2.028545    1.077510   -0.459699   -1.503555
75%      5.150597    2.840360    2.158141    0.463620   -0.426050
max      8.512040    6.973785    7.088385    5.669685    4.842485

       age_Kruijssen        Fe/H        O/Fe
count     323.000000  323.000000  323.000000
mean       11.890557   -1.473180    0.185082
std         0.723695    0.507814    0.290716
min        10.830000   -2.427000   -0.834000
25%        11.520000   -1.809000    0.035500
50%        12.030000   -1.520000    0.220612
75%        12.220000   -1.153000    0.405000
max        13.060000   -0.398000    0.908415
        F275W_abs   F336W_abs   F438W_abs   F606W_abs   F814W_abs  \
count  386.000000  386.000000  386.000000  386.000000  386.000000
mean     4.595203    2.277302    1.326984   -0.273981   -1.285112
std      1.430922    1.191838    1.267251    1.404604    1.495881
min      2.445462    0.377162   -1.161438   -2.886038   -4.195690
25%      3.631326    1.408336    0.430984   -1.274044   -2.296736
50%      4.313475    2.077456    1.142528   -0.371830   -1.389028
75%      5.129208    2.765583    2.188465    0.483786   -0.359633
max      8.512040    6.973785    7.088385    5.669685    4.937985

       age_Kruijssen        Fe/H       Na/Fe
count     386.000000  386.000000  386.000000
mean       11.912202   -1.478974    0.335279
std         0.734269    0.513681    0.286860
min        10.830000   -2.427000   -0.420000
25%        11.520000   -1.813750    0.098500
50%        12.030000   -1.511500    0.347500
75%        12.400000   -1.151500    0.542907
max        13.060000   -0.398000    1.384000

# STOP ANALYSIS OF FULL DATASET HERE